name: Github Actions CI
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: sink/file.tex
        latexmk_use_xelatex: true
    - name: Check pdf file
      run: |
        file cv.pdf | grep -q ' PDF '
    - name: Run deploy script
      run: |
        git config user.name "spicyriceball"
        git config user.email "spicyriceballs@protonmail.com"
        git add sink/file.pdf && git commit -am "[skip ci] automated push" && git push
